# Generated by Django 5.0.6 on 2026-04-23 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringCare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='Ex: Vermifugation, Soins dentaires', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency_value', models.PositiveIntegerField(help_text='Ex: 3')),
                ('frequency_unit', models.CharField(choices=[('day', 'Jour(s)'), ('week', 'Semaine(s)'), ('month', 'Mois'), ('year', 'An(s)')], default='month', max_length=10)),
                ('start_date', models.DateField()),
                ('last_done_at', models.DateField(blank=True, null=True)),
                ('next_due_at', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_cares', to='animals.animal')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_cares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soin récurrent',
                'verbose_name_plural': 'Soins récurrents',
                'db_table': 'recurring_cares',
                'ordering': ['next_due_at'],
            },
        ),
        migrations.CreateModel(
            name='CareEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('performed_at', models.DateField()),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'À faire'), ('done', 'Réalisé'), ('skipped', 'Ignoré'), ('overdue', 'En retard')], default='done', max_length=20)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_events', to=settings.AUTH_USER_MODEL)),
                ('recurring_care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='care.recurringcare')),
            ],
            options={
                'verbose_name': 'Événement de soin',
                'verbose_name_plural': 'Événements de soins',
                'db_table': 'care_events',
                'ordering': ['-performed_at'],
            },
        ),
    ]
