# Generated by Django 5.0.6 on 2026-04-23 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(choices=[('equine', 'Équidé'), ('bovine', 'Bovin'), ('ovine', 'Ovin'), ('caprine', 'Caprin'), ('porcine', 'Porcin'), ('canine', 'Canin'), ('feline', 'Félin'), ('avian', 'Avicole'), ('other', 'Autre')], max_length=50)),
                ('breed', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Mâle'), ('female', 'Femelle'), ('unknown', 'Inconnu')], default='unknown', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('identification_number', models.CharField(blank=True, db_index=True, help_text="Numéro de tatouage, puce, ou SIRE selon l'espèce", max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/photos/')),
                ('notes', models.TextField(blank=True)),
                ('department_code', models.CharField(blank=True, help_text='Code département français (ex: 31, 75, 2A)', max_length=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
                'db_table': 'animals',
                'ordering': ['name'],
            },
        ),
    ]
