# Generated by Django 5.0.6 on 2026-04-23 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('species', models.CharField(help_text="Espèce concernée (ou 'all')", max_length=50)),
                ('min_age_months', models.PositiveIntegerField(blank=True, help_text='Âge minimum en mois', null=True)),
                ('max_age_months', models.PositiveIntegerField(blank=True, help_text='Âge maximum en mois', null=True)),
                ('department_codes', models.JSONField(blank=True, default=list, help_text='Liste de codes département (vide = national)')),
                ('frequency_days', models.PositiveIntegerField(help_text='Fréquence de rappel en jours (ex: 365 pour annuel)')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Règle de vaccination',
                'verbose_name_plural': 'Règles de vaccination',
                'db_table': 'vaccination_rules',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('administered_by', models.CharField(blank=True, help_text='Nom du vétérinaire', max_length=255)),
                ('administered_at', models.DateField()),
                ('next_due_at', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='vaccinations.vaccinationrule')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'db_table': 'vaccination_records',
                'ordering': ['-administered_at'],
            },
        ),
    ]
